name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

# Définition des permissions nécessaires
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.8
        
    - name: Build with Gradle
      run: gradle build --no-daemon
      
    - name: Calculate JAR Hash
      id: hash
      shell: pwsh
      run: |
        $jar = Get-ChildItem -Path "build/libs" -Filter "*.jar" | Select-Object -First 1
        $hash = Get-FileHash -Path $jar.FullName -Algorithm SHA256
        echo "HASH=$($hash.Hash)" >> $env:GITHUB_ENV
        echo "JAR_NAME=$($jar.Name)" >> $env:GITHUB_ENV
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: raven-bs-plus
        path: build/libs/*.jar
        
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.8
        
    - name: Build with Gradle
      run: gradle build --no-daemon
      
    - name: Calculate JAR Hash
      id: hash
      shell: pwsh
      run: |
        $jar = Get-ChildItem -Path "build/libs" -Filter "*.jar" | Select-Object -First 1
        $hash = Get-FileHash -Path $jar.FullName -Algorithm SHA256
        echo "HASH=$($hash.Hash)" >> $env:GITHUB_ENV
        echo "JAR_NAME=$($jar.Name)" >> $env:GITHUB_ENV
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      shell: bash
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        files: ./build/libs/*.jar
        generate_release_notes: true
        body: |
          ## RavenBS-Plus-Plus v${{ env.VERSION }}
          
          ### Hash de sécurité
          **Fichier**: ${{ env.JAR_NAME }}
          **SHA256**: ${{ env.HASH }}
          
          ### Vérification d'intégrité
          Pour vérifier l'intégrité du fichier sur Windows :
          ```powershell
          Get-FileHash -Path "${{ env.JAR_NAME }}" -Algorithm SHA256
          ```
          
          Pour vérifier l'intégrité sur Linux/Mac :
          ```bash
          shasum -a 256 "${{ env.JAR_NAME }}"
          ```
          
          Le hash doit correspondre à celui indiqué ci-dessus.
