name: Update Version in README

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update version in README
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          # Remove 'v' prefix if present
          VERSION=${VERSION#v}
          # Update the version in README.md
          sed -i "s/Current version: [0-9]\+\.[0-9]\+\.[0-9]\+/Current version: ${VERSION}/" README.md
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update version to ${GITHUB_REF#refs/tags/} in README" || exit 0
          git push
